### ISSUE TITLE
Small filename gripe - no init.lua

### ISSUE THREAD

**Issue by 1bardesign** [megagrump/nativefs#3]
Currently the file naming is a little bit "dirty" for use directly out of the repo (eg as a git submodule).

To comply with MIT license, the license text must be kept around.
But the `nativefs.lua` file does not have the MIT text embedded; it's in the readme.

So, the require path in practice ends up looking like `require("lib.nativefs.nativefs")` for `nativefs` under `lib/nativefs`

To remedy this the user must either:
- Rename `nativefs.lua` to `init.lua`, so it's still alongside the readme with the license text
- Move the file out of the directory completely and append the license text inline

Doing both of these without upstream changing obviously make merging in upstream changes from you somewhat annoying - would be much nicer to just `git pull`!

I'd appreciate if the intended lua module could be renamed to `init.lua` as is standard for many lua libraries and supported by love out of the box. Happy to submit a PR if you can't be bothered but accept that it'd help :+1:

**Comment by megagrump** [comment]
Good point. I will add the license text at the top of nativefs.lua.

**Comment by 1bardesign** [comment]
Thanks!

As a note, I've renamed to `init.lua` for my own purposes internally to keep the repo connection as it'd be nice to merge in upstream changes as they come without having to copy it out again, but good to know you intend we just vendor in the file directly.
The double-name in the `require` oath irks me, but I understand it's not a correctness problem. It's your module and you can organise it how you like ;)

**Comment by megagrump** [comment]
There's an `init.lua` file now. Thanks.

**Comment by 1bardesign** [comment]
:100: :+1: :sparkles:
